---

# Quick playbook to ping, ssh (via nc) and snmpwalk (assume v2 with comm string of public)
#  Output saved to a csv file.
# Ver 1.0
#
# Update the inventory via:
#  /etc/ansible/hosts
# Run the playbook via:
#  rm test_connectivity_results.csv; ansible-playbook test_connectivity.yaml
#

- name: WOW Test Connectivity
  hosts: all
  #hosts: nul-wow-20
  connection: local
  gather_facts: false

  vars:
    # Output to save the results.
    csv_file: /root/test_connectivity_results.csv

  tasks:
    - name: Testing Ping to the device
      tags:
        - ping
        - all
      shell: /usr/bin/fping {{ inventory_hostname }}
      register: ping_result
      ignore_errors: true
      delegate_to: localhost

    - name: Testing SSH via nc to the device
      tags:
        - ssh
        - all
      #shell: ssh -o ConnectTimeout=5 {{ inventory_hostname }} exit
      shell: /usr/bin/nc -zvnw1 {{ inventory_hostname }} 22 || echo "ssh is DOWN"
      register: ssh_result
      ignore_errors: true
      delegate_to: localhost

    - name: Testing SNMP to the device
      tags:
        - snmp
        - all
      shell: snmpwalk -v 2c -c public {{ inventory_hostname }} 1.3.6.1.2.1.1.5.0
      register: snmp_result
      ignore_errors: true
      delegate_to: localhost

    - name: Create a CSV file
      local_action:
        module: file
        path: "{{ csv_file }}"
        state: touch
      delegate_to: localhost

    - name: Append Ping result to the CSV
      local_action:
        module: lineinfile
        path: "{{ csv_file }}"
        line: "{{ inventory_hostname }},Ping,{{ 'SUCCESS' if ping_result.rc == 0 else 'FAILED' }}"
      delegate_to: localhost

    - name: Append SSH result to the CSV
      local_action:
        module: lineinfile
        path: "{{ csv_file }}"
        line: "{{ inventory_hostname }},SSH,{{ 'SUCCESS' if ssh_result.rc == 0 else 'FAILED' }}"
      delegate_to: localhost

    - name: Append SNMP result to the CSV
      local_action:
        module: lineinfile
        path: "{{ csv_file }}"
        line: "{{ inventory_hostname }},SNMP,{{ 'SUCCESS' if snmp_result.rc == 0 else 'FAILED' }}"

# EOF
