# Quick playbook to ping, ssh (via nc) and snmpwalk (assume v2 with comm string of ddgsoa10)
#  Output saved to a csv file.
# Ver 1.2
#

- name: Connectivity testing PING, SSH and SNMP
  hosts: all
  #hosts: nul-w*
  connection: local
  gather_facts: false

  vars:
    # Output to save the results.
    csv_file: /root/test_connectivity_results.csv

  tasks:
    - name: Testing Ping to the device
      tags:
        - ping
      shell: /usr/bin/fping {{ inventory_hostname }}
      register: ping_result
      ignore_errors: true
      delegate_to: localhost

    - name: Testing SSH via nc to the device
      tags:
        - ssh
      #shell: ssh -o ConnectTimeout=5 {{ inventory_hostname }} exit   # Turned off as too hard at the moment. Will just nc to port
      #Sample NetCat on port 22:    nc -vn -w1 10.37.32.244 22
      shell: /usr/bin/nc -vnw1 {{ inventory_hostname }} 22
      register: ssh_result
      ignore_errors: true
      delegate_to: localhost

    - name: Testing SNMP to the device
      tags:
        - snmp
      #shell: snmpwalk -v2c -c {{ inventory_hostname.comms_vstring }} {{ inventory_hostname }} 1.3.6.1.2.1.1.5.0 # Not used at the moment. Too slow
      shell: /usr/bin/nc -zuvnw1 {{ inventory_hostname }} 161
      register: snmp_result
      ignore_errors: true
      delegate_to: localhost

    - name: Create a CSV file
      tags:
        - ping
        - ssh
        - snmp
      local_action:
        module: file
        path: "{{ csv_file }}"
        state: touch
      delegate_to: localhost

    - name: Append Ping result to the CSV
      tags:
        - ping
      local_action:
        module: lineinfile
        path: "{{ csv_file }}"
        line: "{{ inventory_hostname }},Ping,{{ 'SUCCESS' if ping_result.rc == 0 else 'FAILED' }}"
      delegate_to: localhost

    - name: Append SSH result to the CSV
      tags:
        - ssh
      local_action:
        module: lineinfile
        path: "{{ csv_file }}"
        line: "{{ inventory_hostname }},SSH,{{ ssh_result.stderr | replace('(UNKNOWN) ', '') }}"
      delegate_to: localhost

    - name: Append SNMP result to the CSV
      tags:
        - snmp
      local_action:
        module: lineinfile
        path: "{{ csv_file }}"
        line: "{{ inventory_hostname }},SNMP,{{ snmp_result.stderr | replace('(UNKNOWN) ', '') }}"
      delegate_to: localhost

# EOF
