---
- name: Add a local user account on Windows
  hosts: all
  gather_facts: false

- name: Ensure user sysadmin_local is present
  win_user:
    name: local_admin
    password: password123
    fullname: Local user account for OOB support
    description : Local admin account
    password_never_expires: yes
    state: present
    groups:
      - Administrators
    tags: win_user_create

- name: Remove user sysadmin_local
  win_user:
    name: local_admin
    state: absent
    tags: win_user_delete
